// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyxixyzcrfhinvyxpsdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5eGl4eXpjcmZoaW52eXhwc2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTUwMzcsImV4cCI6MjA2NDk5MTAzN30.5LJ_dFZ5gLXIlBz3rECo5sXoCd3A67l1K3D1b9opNtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);